name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Set up Heroku CLI
    - name: Set up Heroku
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh
        heroku --version

    # Log in to Heroku
    - name: Log in to Heroku
      run: heroku auth:token
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    # Additional Heroku commands here
    - name: Deploy to Heroku
      run: |
        heroku container:push web -a ${{ secrets.HEROKU_APP_NAME }}
        heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
